/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2017-06-13 10:33:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("      <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Free Bootstrap Admin Template : Binary Admin</title>\r\n");
      out.write("\t<!-- BOOTSTRAP STYLES-->\r\n");
      out.write("    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("     <!-- FONTAWESOME STYLES-->\r\n");
      out.write("    <link href=\"assets/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("     <!-- MORRIS CHART STYLES-->\r\n");
      out.write("    <link href=\"assets/js/morris/morris-0.4.3.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <!-- CUSTOM STYLES-->\r\n");
      out.write("    <link href=\"assets/css/custom.css\" rel=\"stylesheet\" />\r\n");
      out.write("     <!-- GOOGLE FONTS-->\r\n");
      out.write("   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-cls-top \" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".sidebar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.html\">Binary admin</a> \r\n");
      out.write("            </div>\r\n");
      out.write("  <div style=\"color: white;\r\n");
      out.write("padding: 15px 50px 5px 50px;\r\n");
      out.write("float: right;\r\n");
      out.write("font-size: 16px;\"> Last access : 30 May 2014 &nbsp; <a href=\"login.html\" class=\"btn btn-danger square-btn-adjust\">Logout</a> </div>\r\n");
      out.write("        </nav>   \r\n");
      out.write("           <!-- /. NAV TOP  -->\r\n");
      out.write("                <nav class=\"navbar-default navbar-side\" role=\"navigation\">\r\n");
      out.write("            <div class=\"sidebar-collapse\">\r\n");
      out.write("                <ul class=\"nav\" id=\"main-menu\">\r\n");
      out.write("\t\t\t\t<li class=\"text-center\">\r\n");
      out.write("                    <img src=\"assets/img/find_user.png\" class=\"user-image img-responsive\"/>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"active-menu\"  href=\"index.html\"><i class=\"fa fa-dashboard fa-3x\"></i> Dashboard</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a  href=\"ui.html\"><i class=\"fa fa-desktop fa-3x\"></i> UI Elements</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a  href=\"tab-panel.html\"><i class=\"fa fa-qrcode fa-3x\"></i> Tabs & Panels</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t\t   <li  >\r\n");
      out.write("                        <a   href=\"chart.html\"><i class=\"fa fa-bar-chart-o fa-3x\"></i> Morris Charts</a>\r\n");
      out.write("                    </li>\t\r\n");
      out.write("                      <li  >\r\n");
      out.write("                        <a  href=\"table.html\"><i class=\"fa fa-table fa-3x\"></i> Table Examples</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li  >\r\n");
      out.write("                        <a  href=\"form.html\"><i class=\"fa fa-edit fa-3x\"></i> Forms </a>\r\n");
      out.write("                    </li>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t <li  >\r\n");
      out.write("                        <a   href=\"login.html\"><i class=\"fa fa-bolt fa-3x\"></i> Login</a>\r\n");
      out.write("                    </li>\t\r\n");
      out.write("                     <li  >\r\n");
      out.write("                        <a   href=\"registeration.html\"><i class=\"fa fa-laptop fa-3x\"></i> Registeration</a>\r\n");
      out.write("                    </li>\t\r\n");
      out.write("\t\t\t\t\t                   \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-sitemap fa-3x\"></i> Multi-Level Dropdown<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Second Level Link</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Second Level Link</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Second Level Link<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                                <ul class=\"nav nav-third-level\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">Third Level Link</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">Third Level Link</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">Third Level Link</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("\r\n");
      out.write("                                </ul>\r\n");
      out.write("                               \r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </li>  \r\n");
      out.write("                  <li  >\r\n");
      out.write("                        <a  href=\"blank.html\"><i class=\"fa fa-square-o fa-3x\"></i> Blank Page</a>\r\n");
      out.write("                    </li>\t\r\n");
      out.write("                </ul>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </nav>  \r\n");
      out.write("        <!-- /. NAV SIDE  -->\r\n");
      out.write("        <div id=\"page-wrapper\" >\r\n");
      out.write("            <div id=\"page-inner\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                     <h2>Admin Dashboard</h2>   \r\n");
      out.write("                        <h5>Welcome Jhon Deo , Love to see you back. </h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>              \r\n");
      out.write("                 <!-- /. ROW  -->\r\n");
      out.write("                  <hr />\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6 col-xs-6\">           \r\n");
      out.write("\t\t\t<div class=\"panel panel-back noti-box\">\r\n");
      out.write("                <span class=\"icon-box bg-color-red set-icon\">\r\n");
      out.write("                    <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"text-box\" >\r\n");
      out.write("                    <p class=\"main-text\">120 New</p>\r\n");
      out.write("                    <p class=\"text-muted\">Messages</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-6\">           \r\n");
      out.write("\t\t\t<div class=\"panel panel-back noti-box\">\r\n");
      out.write("                <span class=\"icon-box bg-color-green set-icon\">\r\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"text-box\" >\r\n");
      out.write("                    <p class=\"main-text\">30 Tasks</p>\r\n");
      out.write("                    <p class=\"text-muted\">Remaining</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-6\">           \r\n");
      out.write("\t\t\t<div class=\"panel panel-back noti-box\">\r\n");
      out.write("                <span class=\"icon-box bg-color-blue set-icon\">\r\n");
      out.write("                    <i class=\"fa fa-bell-o\"></i>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"text-box\" >\r\n");
      out.write("                    <p class=\"main-text\">240 New</p>\r\n");
      out.write("                    <p class=\"text-muted\">Notifications</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-6\">           \r\n");
      out.write("\t\t\t<div class=\"panel panel-back noti-box\">\r\n");
      out.write("                <span class=\"icon-box bg-color-brown set-icon\">\r\n");
      out.write("                    <i class=\"fa fa-rocket\"></i>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"text-box\" >\r\n");
      out.write("                    <p class=\"main-text\">3 Orders</p>\r\n");
      out.write("                    <p class=\"text-muted\">Pending</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("                 <!-- /. ROW  -->\r\n");
      out.write("                <hr />                \r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 col-sm-12 col-xs-12\">           \r\n");
      out.write("\t\t\t<div class=\"panel panel-back noti-box\">\r\n");
      out.write("                <span class=\"icon-box bg-color-blue\">\r\n");
      out.write("                    <i class=\"fa fa-warning\"></i>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"text-box\" >\r\n");
      out.write("                    <p class=\"main-text\">52 Important Issues to Fix </p>\r\n");
      out.write("                    <p class=\"text-muted\">Please fix these issues to work smooth</p>\r\n");
      out.write("                    <p class=\"text-muted\">Time Left: 30 mins</p>\r\n");
      out.write("                    <hr />\r\n");
      out.write("                    <p class=\"text-muted\">\r\n");
      out.write("                          <span class=\"text-muted color-bottom-txt\"><i class=\"fa fa-edit\"></i>\r\n");
      out.write("                               Lorem ipsum dolor sit amet, consectetur adipiscing elit gthn. \r\n");
      out.write("                              Lorem ipsum dolor sit amet, consectetur adipiscing elit gthn. \r\n");
      out.write("                               </span>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-md-3 col-sm-12 col-xs-12\">\r\n");
      out.write("                        <div class=\"panel back-dash\">\r\n");
      out.write("                               <i class=\"fa fa-dashboard fa-3x\"></i><strong> &nbsp; SPEED</strong>\r\n");
      out.write("                             <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipiscing sit ametsit amet elit ftr. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-12 col-xs-12 \">\r\n");
      out.write("                        <div class=\"panel \">\r\n");
      out.write("          <div class=\"main-temp-back\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xs-6\"> <i class=\"fa fa-cloud fa-3x\"></i> Newyork City </div>\r\n");
      out.write("                <div class=\"col-xs-6\">\r\n");
      out.write("                  <div class=\"text-temp\"> 10° </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("                     <div class=\"panel panel-back noti-box\">\r\n");
      out.write("                <span class=\"icon-box bg-color-green set-icon\">\r\n");
      out.write("                    <i class=\"fa fa-desktop\"></i>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"text-box\" >\r\n");
      out.write("                    <p class=\"main-text\">Display</p>\r\n");
      out.write("                    <p class=\"text-muted\">Looking Good</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("    </div>\r\n");
      out.write("                        \r\n");
      out.write("        </div>\r\n");
      out.write("                 <!-- /. ROW  -->\r\n");
      out.write("                <div class=\"row\"> \r\n");
      out.write("                    \r\n");
      out.write("                      \r\n");
      out.write("                               <div class=\"col-md-9 col-sm-12 col-xs-12\">                     \r\n");
      out.write("                    <div class=\"panel panel-default\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                            Bar Chart Example\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <div id=\"morris-bar-chart\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>            \r\n");
      out.write("                </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-12 col-xs-12\">                       \r\n");
      out.write("                    <div class=\"panel panel-primary text-center no-boder bg-color-green\">\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <i class=\"fa fa-bar-chart-o fa-5x\"></i>\r\n");
      out.write("                            <h3>120 GB </h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-footer back-footer-green\">\r\n");
      out.write("                           Disk Space Available\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"panel panel-primary text-center no-boder bg-color-red\">\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <i class=\"fa fa-edit fa-5x\"></i>\r\n");
      out.write("                            <h3>20,000 </h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-footer back-footer-red\">\r\n");
      out.write("                            Articles Pending\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>                         \r\n");
      out.write("                        </div>\r\n");
      out.write("                \r\n");
      out.write("           </div>\r\n");
      out.write("                 <!-- /. ROW  -->\r\n");
      out.write("                <div class=\"row\" >\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-12 col-xs-12\">\r\n");
      out.write("  <div class=\"panel panel-primary text-center no-boder bg-color-green\">\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <i class=\"fa fa-comments-o fa-5x\"></i>\r\n");
      out.write("                            <h4>200 New Comments </h4>\r\n");
      out.write("                             <h4>See All Comments  </h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-footer back-footer-green\">\r\n");
      out.write("                             <i class=\"fa fa-rocket fa-5x\"></i>\r\n");
      out.write("                            Lorem ipsum dolor sit amet sit sit, consectetur adipiscing elitsit sit gthn ipsum dolor sit amet ipsum dolor sit amet\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-9 col-sm-12 col-xs-12\">\r\n");
      out.write("               \r\n");
      out.write("                    <div class=\"panel panel-default\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                           Responsive Table Example\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table table-striped table-bordered table-hover\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>#</th>\r\n");
      out.write("                                            <th>First Name</th>\r\n");
      out.write("                                            <th>Last Name</th>\r\n");
      out.write("                                            <th>Username</th>\r\n");
      out.write("                                             <th>User No.</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>1</td>\r\n");
      out.write("                                            <td>Mark</td>\r\n");
      out.write("                                            <td>Otto</td>\r\n");
      out.write("                                            <td>@mdo</td>\r\n");
      out.write("                                            <td>100090</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>2</td>\r\n");
      out.write("                                            <td>Jacob</td>\r\n");
      out.write("                                            <td>Thornton</td>\r\n");
      out.write("                                            <td>@fat</td>\r\n");
      out.write("                                            <td>100090</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>3</td>\r\n");
      out.write("                                            <td>Larry</td>\r\n");
      out.write("                                            <td>the Bird</td>\r\n");
      out.write("                                            <td>@twitter</td>\r\n");
      out.write("                                            <td>100090</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                         <tr>\r\n");
      out.write("                                            <td>1</td>\r\n");
      out.write("                                            <td>Mark</td>\r\n");
      out.write("                                            <td>Otto</td>\r\n");
      out.write("                                            <td>@mdo</td>\r\n");
      out.write("                                            <td>100090</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>2</td>\r\n");
      out.write("                                            <td>Jacob</td>\r\n");
      out.write("                                            <td>Thornton</td>\r\n");
      out.write("                                            <td>@fat</td>\r\n");
      out.write("                                            <td>100090</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>3</td>\r\n");
      out.write("                                            <td>Larry</td>\r\n");
      out.write("                                            <td>the Bird</td>\r\n");
      out.write("                                            <td>@twitter</td>\r\n");
      out.write("                                            <td>100090</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                 <!-- /. ROW  -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 col-sm-12 col-xs-12\">\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"chat-panel panel panel-default chat-boder chat-panel-head\" >\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                            <i class=\"fa fa-comments fa-fw\"></i>\r\n");
      out.write("                            Chat Box\r\n");
      out.write("                            <div class=\"btn-group pull-right\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-default btn-xs dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                                    <i class=\"fa fa-chevron-down\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <ul class=\"dropdown-menu slidedown\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <i class=\"fa fa-refresh fa-fw\"></i>Refresh\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <i class=\"fa fa-check-circle fa-fw\"></i>Available\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <i class=\"fa fa-times fa-fw\"></i>Busy\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <i class=\"fa fa-clock-o fa-fw\"></i>Away\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"divider\"></li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\">\r\n");
      out.write("                                            <i class=\"fa fa-sign-out fa-fw\"></i>Sign Out\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <ul class=\"chat-box\">\r\n");
      out.write("                                <li class=\"left clearfix\">\r\n");
      out.write("                                    <span class=\"chat-img pull-left\">\r\n");
      out.write("                                        <img src=\"assets/img/1.png\" alt=\"User\" class=\"img-circle\" />\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"chat-body\">                                        \r\n");
      out.write("                                            <strong >Jack Sparrow</strong>\r\n");
      out.write("                                            <small class=\"pull-right text-muted\">\r\n");
      out.write("                                                <i class=\"fa fa-clock-o fa-fw\"></i>12 mins ago\r\n");
      out.write("                                            </small>                                      \r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"right clearfix\">\r\n");
      out.write("                                    <span class=\"chat-img pull-right\">\r\n");
      out.write("\r\n");
      out.write("                                        <img src=\"assets/img/2.png\" alt=\"User\" class=\"img-circle\" />\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"chat-body clearfix\">\r\n");
      out.write("                                        \r\n");
      out.write("                                            <small class=\" text-muted\">\r\n");
      out.write("                                                <i class=\"fa fa-clock-o fa-fw\"></i>13 mins ago</small>\r\n");
      out.write("                                            <strong class=\"pull-right\">Jhonson Deed</strong>\r\n");
      out.write("                                      \r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"left clearfix\">\r\n");
      out.write("                                    <span class=\"chat-img pull-left\">\r\n");
      out.write("                                         <img src=\"assets/img/3.png\" alt=\"User\" class=\"img-circle\" />\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"chat-body clearfix\">\r\n");
      out.write("                                        \r\n");
      out.write("                                            <strong >Jack Sparrow</strong>\r\n");
      out.write("                                            <small class=\"pull-right text-muted\">\r\n");
      out.write("                                                <i class=\"fa fa-clock-o fa-fw\"></i>14 mins ago</small>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"right clearfix\">\r\n");
      out.write("                                    <span class=\"chat-img pull-right\">\r\n");
      out.write("                                         <img src=\"assets/img/4.png\" alt=\"User\" class=\"img-circle\" />\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"chat-body clearfix\">\r\n");
      out.write("                                      \r\n");
      out.write("                                            <small class=\" text-muted\">\r\n");
      out.write("                                                <i class=\"fa fa-clock-o fa-fw\"></i>15 mins ago</small>\r\n");
      out.write("                                            <strong class=\"pull-right\">Jhonson Deed</strong>\r\n");
      out.write("                                       \r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                    <li class=\"left clearfix\">\r\n");
      out.write("                                    <span class=\"chat-img pull-left\">\r\n");
      out.write("                                        <img src=\"assets/img/1.png\" alt=\"User\" class=\"img-circle\" />\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"chat-body\">                                        \r\n");
      out.write("                                            <strong >Jack Sparrow</strong>\r\n");
      out.write("                                            <small class=\"pull-right text-muted\">\r\n");
      out.write("                                                <i class=\"fa fa-clock-o fa-fw\"></i>12 mins ago\r\n");
      out.write("                                            </small>                                      \r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"right clearfix\">\r\n");
      out.write("                                    <span class=\"chat-img pull-right\">\r\n");
      out.write("                                       <img src=\"assets/img/2.png\" alt=\"User\" class=\"img-circle\" />\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"chat-body clearfix\">\r\n");
      out.write("                                        \r\n");
      out.write("                                            <small class=\" text-muted\">\r\n");
      out.write("                                                <i class=\"fa fa-clock-o fa-fw\"></i>13 mins ago</small>\r\n");
      out.write("                                            <strong class=\"pull-right\">Jhonson Deed</strong>\r\n");
      out.write("                                      \r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"panel-footer\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <input id=\"btn-input\" type=\"text\" class=\"form-control input-sm\" placeholder=\"Type your message to send...\" />\r\n");
      out.write("                                <span class=\"input-group-btn\">\r\n");
      out.write("                                    <button class=\"btn btn-warning btn-sm\" id=\"btn-chat\">\r\n");
      out.write("                                        Send\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-sm-12 col-xs-12\">\r\n");
      out.write("                         <div class=\"panel panel-default\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                           Label Examples\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <span class=\"label label-default\">Default</span>\r\n");
      out.write("<span class=\"label label-primary\">Primary</span>\r\n");
      out.write("<span class=\"label label-success\">Success</span>\r\n");
      out.write("<span class=\"label label-info\">Info</span>\r\n");
      out.write("<span class=\"label label-warning\">Warning</span>\r\n");
      out.write("<span class=\"label label-danger\">Danger</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                         \r\n");
      out.write("                         <div class=\"panel panel-default\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                            Donut Chart Example\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <div id=\"morris-donut-chart\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                      \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>     \r\n");
      out.write("                 <!-- /. ROW  -->           \r\n");
      out.write("    </div>\r\n");
      out.write("             <!-- /. PAGE INNER  -->\r\n");
      out.write("            </div>\r\n");
      out.write("         <!-- /. PAGE WRAPPER  -->\r\n");
      out.write("        </div>\r\n");
      out.write("     <!-- /. WRAPPER  -->\r\n");
      out.write("    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->\r\n");
      out.write("    <!-- JQUERY SCRIPTS -->\r\n");
      out.write("    <script src=\"assets/js/jquery-1.10.2.js\"></script>\r\n");
      out.write("      <!-- BOOTSTRAP SCRIPTS -->\r\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- METISMENU SCRIPTS -->\r\n");
      out.write("    <script src=\"assets/js/jquery.metisMenu.js\"></script>\r\n");
      out.write("     <!-- MORRIS CHART SCRIPTS -->\r\n");
      out.write("     <script src=\"assets/js/morris/raphael-2.1.0.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/morris/morris.js\"></script>\r\n");
      out.write("      <!-- CUSTOM SCRIPTS -->\r\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
